# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-01 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='group_num',
            field=models.IntegerField(default=1),
        ),
    ]
