# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-10 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20181103_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='images'),
        ),
    ]
