# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-13 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20181110_1657'),
        ('core', '0010_auto_20181107_1033'),
    ]

    operations = [
    ]
