# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-24 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0003_auto_20181024_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='category',
            field=models.CharField(max_length=255),
        ),
    ]
